### ISSUE TITLE
Can not work on master(f4b17c1) branch now

### ISSUE THREAD

**Issue by snowyu** [voxelize/voxelize#18]
`yarn --cwd transport run proto` should update and the demo should update too.

**Comment by shaoruu** [comment]
Hi, thank you for your interest in Voxelize! We planned on rewriting the entire engine because we felt like everything was too messy, but then we haven't gotten the time to actually do it yet, so the main branch is a mess now 😆

You can check out the [orignal version](https://github.com/voxelize/voxelize/tree/legacy) of Voxelize, which contains a working version of the demo!

**Comment by snowyu** [comment]
Alright, what's the goal? I'm looking for a new voxel engine that:

*   Is cross-platform and works on both PCs and mobile devices.
*   Supports voxels that can be resized, with higher-end GPUs allowing for smaller, more detailed voxels.
*   Supports basic shapes like lines, faces, arcs, etc.
*   Allows for the creation of new NPCs through the combination of multiple layers of voxels and shapes.
*   Supports LOD rendering like in [https://github.com/skishore/wave](https://github.com/skishore/wave).
*   Can load assets in different ways, such as preloading, lazy loading, client-side loading, or server-side loading.
*   Supports loading of 3D models similar to SVG (as shown in [https://zzz.dog/](https://zzz.dog/)).
*   Has a scalable coordinate system that can automatically expand based on the size of the world map, whether it's a fixed-size map or an endless map, going from i8->i16->i32-i64->i128->... as needed.
*   Has a complete physics engine with adaptable interfaces, including node combination and skeletal animation.
*   Has an extensible plugin system, with the entire system made up of plugins, including rendering, asset management, physics engines, input devices, network communication, and map systems etc.

Currently I am using minetest for open education, but I've found too more limits on it. 

### refs

* [WAVE: WebAssembly Voxel Engine](https://github.com/skishore/wave)
* [noa-engine](https://github.com/fenomas/noa)
* [cubzh](https://github.com/cubzh/cubzh)
* [Cubiquity](https://github.com/DavidWilliams81/cubiquity)
