### ISSUE TITLE
World gets corrupted

### ISSUE THREAD

**Issue by AntonioNoack** [voxelize/voxelize#22]
Hi 😊,

I wrote a thank-you sign, cleared up the hub a little,
and when I came back, the T was broken.

I repaired it, cleared up the hub a little more,
and when I then came back, my sign was pretty broken.
![image](https://github.com/voxelize/voxelize/assets/20659579/a436662e-96f6-4839-9cbd-e640b62ce916)

Everything was within ~15 mins, so I doubt another player was it, especially because I didn't see any other player.

Besides that, I also noticed that when placing blocks on the most-outside block, they don't get updated visually until a neighboring block is placed.
(I played on https://shaoruu.io/, if that matters)

**Comment by shaoruu** [comment]
so you were the one clearing up the hub!!! thanks for the builds haha, did you also build the blue tower? 

also, i can't think of any reason the world would be corrupting 🤔 i was wondering why the thank you sign looked weird too hahahaha, but there is NO WAY in this library that corruption occurs (i don't think so)

**Comment by AntonioNoack** [comment]
I didn't build the blue tower, that one is insane xD.
